#!/usr/bin/env python3
"""Generate the union of direct native-runtime bindings for the shipped cores."""
from pathlib import Path
import argparse
import re
import subprocess

ROOT = Path(__file__).resolve().parent.parent


def collect_imports(cores):
    """Each undefined name: its kind, and whether every core that imports it
    does so weakly (a weak reference the title need not satisfy)."""
    imports = {}
    for core in cores:
        symbols = subprocess.check_output(['readelf', '--dyn-syms', '-W', str(core)], text=True)
        for line in symbols.splitlines():
            fields = line.split()
            if len(fields) < 8 or fields[6] != 'UND':
                continue
            name, kind, weak = fields[7], fields[3], fields[4] == 'WEAK'
            if not re.fullmatch(r'[A-Za-z_][A-Za-z0-9_]*', name) or kind not in ('FUNC', 'OBJECT', 'NOTYPE'):
                raise ValueError(f'Unsupported native core import: {name} ({kind})')
            if name in imports and imports[name][0] != kind:
                raise ValueError(f'Conflicting native import types for {name}')
            imports[name] = (kind, weak and imports.get(name, (kind, True))[1])
    return imports


def generate(imports):
    lines = ['// Generated by tools/core-imports.py; never edit.', '#include <cstring>']
    # The platform layer (my payload SDK fork, include/ps5platform/libc.h) for
    # what the console's libc lacks or refuses: a title's opendir is refused,
    # the *at functions resolve to nothing (only libkernel_sys has them), and
    # arc4random, utimensat, futimens and clock_nanosleep have no export at all.
    aliases = {'opendir': 'ps5_opendir', 'readdir': 'ps5_readdir', 'closedir': 'ps5_closedir',
               'dirfd': 'ps5_dirfd', 'fdopendir': 'ps5_fdopendir',
               'openat': 'ps5_openat', 'unlinkat': 'ps5_unlinkat', 'fchmodat': 'ps5_fchmodat',
               'fstatat': 'ps5_fstatat', 'mkdirat': 'ps5_mkdirat', 'renameat': 'ps5_renameat',
               'utimensat': 'ps5_utimensat', 'futimens': 'ps5_futimens',
               'clock_nanosleep': 'ps5_clock_nanosleep',
               'arc4random_buf': 'ps5_arc4random_buf',
               'arc4random_uniform': 'ps5_arc4random_uniform',
               'fstatvfs': 'ps5_fstatvfs',
               'localtime_r': 'rtime_localtime', 'rewinddir': 'ps5_rewinddir',
               # src/core_threads_ps5.cpp: libkernel cannot attribute a thread
               # created from a core's stack, so a factory thread creates it.
               'pthread_create': 'ps5_core_pthread_create',
               # The same lookup runs in the thread-specific-data calls, which a
               # core's std::thread start routine makes itself.
               'pthread_key_create': 'ps5_core_pthread_key_create',
               'pthread_key_delete': 'ps5_core_pthread_key_delete',
               'pthread_getspecific': 'ps5_core_pthread_getspecific',
               'pthread_setspecific': 'ps5_core_pthread_setspecific',
               # src/memory_ps5.cpp: a core allocates from direct memory first, so
               # it cannot starve the libc heap the system libraries depend on.
               'malloc': 'ps5_core_malloc', 'calloc': 'ps5_core_calloc',
               'realloc': 'ps5_core_realloc', 'aligned_alloc': 'ps5_core_aligned_alloc',
               'posix_memalign': 'ps5_core_posix_memalign', 'strdup': 'ps5_core_strdup',
               '_Znwm': 'ps5_core_new', '_Znam': 'ps5_core_new',
               '_ZnwmRKSt9nothrow_t': 'ps5_core_new_nothrow', '_ZnamRKSt9nothrow_t': 'ps5_core_new_nothrow',
               '_ZnwmSt11align_val_t': 'ps5_core_new_aligned', '_ZnamSt11align_val_t': 'ps5_core_new_aligned',
               '_ZnwmSt11align_val_tRKSt9nothrow_t': 'ps5_core_new_aligned_nothrow',
               '_ZnamSt11align_val_tRKSt9nothrow_t': 'ps5_core_new_aligned_nothrow',
               # The platform layer: the SDK resolves this import to nothing.
               'arc4random': 'ps5_arc4random',
               # The platform layer: the console libc's statvfs faults (it
               # rests on statfs, which only libkernel_sys carries).
               'statvfs': 'ps5_statvfs', 'strcasestr': 'ps5_strcasestr',
               'memccpy': 'ps5_memccpy', 'times': 'ps5_times', 'sockatmark': 'ps5_sockatmark',
               'getpwuid': 'ps5_getpwuid', 'gethostbyaddr': 'ps5_gethostbyaddr',
               'gethostbyname': 'ps5_gethostbyname', 'getnameinfo': 'ps5_getnameinfo',
               'gai_strerror': 'ps5_gai_strerror',
               # libc's getcwd calls __getcwd, which only libkernel_sys has.
               'getcwd': 'ps5_getcwd', 'tmpfile': 'ps5_tmpfile',
               'if_nametoindex': 'ps5_if_nametoindex', 'if_indextoname': 'ps5_if_indextoname',
               'mkstemp': 'ps5_mkstemp', 'isatty': 'ps5_isatty', 'link': 'ps5_link',
               'symlink': 'ps5_symlink', 'readlink': 'ps5_readlink', 'fchown': 'ps5_fchown',
               # No system module exports them (RPCS3's wolfSSL, asmjit and network).
               'accept4': 'ps5_accept4', 'getpagesizes': 'ps5_getpagesizes',
               'in6addr_any': 'ps5_in6addr_any',
               # The console refuses FreeBSD's cpuset_t (ERANGE); the platform
               # layer answers through the exported 64-bit mask.
               'pthread_getaffinity_np': 'ps5_pthread_getaffinity_np',
               'pthread_setaffinity_np': 'ps5_pthread_setaffinity_np',
               # It says 16 CPUs where a title's threads run on thirteen.
               'sysconf': 'ps5_sysconf',
               # A thread's thread_local destructors run before libkernel's key
               # destructors, which free its emulated TLS (the platform's cxa.c).
               'pthread_exit': 'ps5_pthread_exit',
               # A title may make no system call; SYS_write is write().
               'syscall': 'ps5_syscall',
               'getpwnam_r': 'ps5_getpwnam_r', 'posix_madvise': 'ps5_posix_madvise',
               'strsignal': 'ps5_strsignal',
               # Only libkernel_sys has them: the imports resolve to nothing.
               'statfs': 'ps5_statfs', 'fstatfs': 'ps5_fstatfs', 'umask': 'ps5_umask',
               'fork': 'ps5_fork', 'setsid': 'ps5_setsid', 'wait4': 'ps5_wait4',
               # src/core_loader_ps5.cpp: the console's, plus dlopen(NULL), the
               # process handle LLVM's JIT asks for.
               'dlopen': 'ps5_cores_dlopen', 'dlsym': 'ps5_cores_dlsym',
               'dlclose': 'ps5_cores_dlclose', 'dlerror': 'ps5_cores_dlerror',
               # Refused to a title (EPERM), even for /app0.
               'realpath': 'ps5_realpath'}
    for index, (name, (kind, weak)) in enumerate(sorted(imports.items())):
        target = aliases.get(name, name)
        declaration = f'void core_import_{index}()' if kind == 'FUNC' else f'char core_import_{index}[]'
        # A weak reference (a thread_local's initialisation routine, gcov's
        # hooks) stays null when nothing in the title defines it, as the
        # loader leaves it for a core.
        attribute = ' __attribute__((weak))' if weak else ''
        lines.append(f'extern "C" {declaration} asm("{target}"){attribute};')
    lines.extend(['extern "C" void *ps5_core_import(const char *name)', '{'])
    for index, name in enumerate(sorted(imports)):
        lines.append(f'    if (!std::strcmp(name, "{name}")) return reinterpret_cast<void *>(&core_import_{index});')
    lines.extend(['    return nullptr;', '}'])
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('cores', type=Path, nargs='+')
    args = parser.parse_args()
    imports = collect_imports(args.cores)
    (ROOT / 'build/core_imports.inc').write_text(generate(imports))
    print(f'core imports: {len(imports)} explicit native bindings for {len(args.cores)} cores')


if __name__ == '__main__':
    main()
