#!/usr/bin/env python3
"""Porpoise - the table of Dolphin's built-in graphics mods (src/porpoise_gfxmods_table.inc).

Reads Dolphin's Sys/Load/GraphicMods (bundled with the core) and writes, for
each game that has mods, which of Porpoise's rows it gets: Bloom, Depth of
field, Hide the HUD (each through Dolphin's "All Games" mods and the game's
own texture definitions), a game's own Bloom mods (De Blob), and a game's own
feature mod (Super Mario Sunshine's native resolution goop).

    tools/make-gfx-mods.py <Sys/Load/GraphicMods> > src/porpoise_gfxmods_table.inc
"""
import json
import os
import sys

root = sys.argv[1]
rows = []
for top in sorted(os.listdir(root)):
    if top.startswith("All Games"):
        continue
    entry = {"groups": set(), "ids": set(), "bloom_off": "", "bloom_blur": "", "own": "", "own_title": ""}
    for here, _, files in os.walk(os.path.join(root, top)):
        if "metadata.json" not in files:
            continue
        rel = os.path.relpath(os.path.join(here, "metadata.json"), root).replace(os.sep, "/")
        meta = json.load(open(os.path.join(here, "metadata.json"), encoding="utf-8"))
        entry["ids"].update(f[:-4] for f in files if f.endswith(".txt"))
        groups = {g["name"] for g in meta.get("groups", [])}
        features = meta.get("features", [])
        if not features:
            entry["groups"].update(groups & {"Bloom", "DOF", "HUD"})
            continue
        title = meta.get("meta", {}).get("title", "")
        if "CustomBloom" in groups:
            if any(f.get("action") == "skip" for f in features):
                entry["bloom_off"] = rel
            else:
                entry["bloom_blur"] = rel
        else:
            entry["own"], entry["own_title"] = rel, title
    for gid in sorted(entry["ids"]):
        rows.append((gid, entry))

print("/* Generated by tools/make-gfx-mods.py from Dolphin's Sys/Load/GraphicMods: don't edit. */")
for gid, e in rows:
    print('    {"%s", %s, %s, %s, "%s", "%s", "%s", "%s"},' % (
        gid, "true" if "Bloom" in e["groups"] else "false", "true" if "DOF" in e["groups"] else "false",
        "true" if "HUD" in e["groups"] else "false", e["bloom_off"], e["bloom_blur"], e["own"], e["own_title"]))
