#!/usr/bin/env python3
# Porpoise - builds src/ui_i18n_table.inc, the menus' translations, from
# i18n/strings.json (every English text the menus show, in order) and
# i18n/<language>.json (English -> translation). A text a language doesn't
# have yet shows in English.
#
# Checks each translation: the same {placeholders} as the English, and for
# Polish and Russian, either no "|" or exactly three forms ("one|few|many")
# when the text counts something with {n}.
#
#   python3 tools/make-i18n.py           writes the table
#   python3 tools/make-i18n.py --check   only reports what's missing or wrong
#
# SPDX-License-Identifier: GPL-3.0-or-later
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# In the order of porpoise::ui::Language after English.
LANGS = ["es", "fr", "pt", "it", "ja", "es-419", "pt-BR", "de", "nl", "pl", "ru", "zh-Hans", "zh-Hant", "ko", "tr"]
THREE_FORMS = {"pl", "ru"}


def c_string(s):
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ord(ch) < 0x20:
            out.append("\\x%02X" % ord(ch))
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def main():
    check_only = "--check" in sys.argv
    strings = json.load(open(os.path.join(ROOT, "i18n", "strings.json"), encoding="utf-8"))
    english = [s["en"] for s in strings]
    tables = {}
    problems = 0
    for lang in LANGS:
        path = os.path.join(ROOT, "i18n", lang + ".json")
        tables[lang] = json.load(open(path, encoding="utf-8")) if os.path.exists(path) else {}
        missing = [e for e in english if not tables[lang].get(e)]
        unknown = [k for k in tables[lang] if k not in english]
        for k in unknown:
            print(f"{lang}: not in strings.json (left out): {k!r}")
        for e in english:
            t = tables[lang].get(e)
            if not t:
                continue
            want = sorted(re.findall(r"\{[a-z_]+\}", e.split("|", 1)[-1] if e.startswith("memcard|") else e))
            forms = t.split("|")
            if len(forms) > 1 and not (lang in THREE_FORMS and len(forms) == 3 and "{n}" in e):
                print(f"{lang}: '|' only for Polish/Russian counts (one|few|many): {e!r} -> {t!r}")
                problems += 1
                continue
            for f in forms:
                got = sorted(re.findall(r"\{[a-z_]+\}", f))
                if got != want:
                    print(f"{lang}: placeholders differ: {e!r} -> {f!r}")
                    problems += 1
        print(f"{lang}: {len(english) - len(missing)} of {len(english)} translated")
    if check_only:
        return 1 if problems else 0
    if problems:
        print("not written: fix the problems above first")
        return 1

    lines = [
        "/* Generated by tools/make-i18n.py from the files in i18n/ - edit those, not this. */",
        "/* clang-format off */",
    ]
    section = None
    for s in strings:
        if s.get("section") != section:
            section = s.get("section")
            lines.append(f"/* {section} */")
        cols = []
        for lang in LANGS:
            t = tables[lang].get(s["en"])
            cols.append(c_string(t) if t else "nullptr")
        lines.append("{" + c_string(s["en"]) + ", {" + ", ".join(cols) + "}},")
    lines.append("/* clang-format on */")
    out = os.path.join(ROOT, "src", "ui_i18n_table.inc")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", out, f"({len(strings)} texts, {len(LANGS)} languages)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
